name: Study CI

on:
  push:
    branches: [ "master" ]
    paths-ignore:
      - '*.md'
  pull_request:
    branches: [ "master" ]
    paths-ignore:
      - '*.md'

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        id: checkout
        uses: actions/checkout@v4

      - name: Make
        id: make
        run: make clean && make all -j4
